---

- include_tasks: encvolume.yml
  when: patroni_encvolume | bool
  tags: [patroni, patroni-encvolume]

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [patroni, patroni-install, patroni-configure]

- import_tasks: install.yml
  tags: [patroni, patroni-install]

- import_tasks: configure.yml
  tags: [patroni, patroni-configure]

- import_tasks: firewalld.yml
  tags: [patroni, patroni-firesalld]

- meta: flush_handlers

- name: Ensure patroni is running
  systemd:
    name: patroni.service
    state: started
    daemon_reload: yes
    enabled: yes
  register: ensure_patroni_is_running
  tags: [patroni]

- include_tasks: createdb.yml
  when: patroni_databases is defined
  tags: [patroni, patroni-createdb]
